services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-h2h3-demo
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
